<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn> <!-- Tắt cảnh báo thiếu XML comment ở các member mặc định -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EduMind.Infrastructure.AI\EduMind.Infrastructure.AI.csproj" />
    <ProjectReference Include="..\EduMind.Infrastructure.Data\EduMind.Infrastructure.Data.csproj" />
    <ProjectReference Include="..\EduMind.Application\EduMind.Application.csproj" />
    <ProjectReference Include="..\EduMind.Domain\EduMind.Domain.csproj" />
  </ItemGroup>

</Project>
